spring:
  application:
    name: pet-love
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/pet-love-database

jwt:
  secret: JGHfsdf80wdewlkb309fgOg7SK1LqzK6eeD0g0BfgOg7S